ct_events:
  - name: Gottesdienst
    song_placements:
      - agenda_item:
          title: Lobpreis
          type: header
        position: after
        songs: "[:-1]" # Alle bis auf den letzten
      - agenda_item:
          title: Abschluss
          type: header
        position: after
        songs: "[-1]" # Nur der letzte
  - name: Fokus
    song_placements:
      - agenda_item:
          type: song
        position: at
        songs: "[:]" # Alle Songs

ct_item_defaults:
  responsible: "[Lobpreisleitung]"
  duration: 300

ct_song_defaults:
  songcategory_id: 4
